// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("rescript/lib/js/belt_Array.js");

console.log("Hello, World!");

function lexer(_chars, _tokens) {
  while(true) {
    var tokens = _tokens;
    var chars = _chars;
    var tail = Belt_Array.sliceToEnd(chars, 1);
    var $$char = Belt_Array.get(chars, 0);
    if ($$char === undefined) {
      return tokens;
    }
    switch ($$char) {
      case "" :
          return tokens;
      case "{" :
          _tokens = Belt_Array.concat(tokens, [{
                  TAG: /* Curly */2,
                  _0: /* Open */0
                }]);
          _chars = tail;
          continue ;
      case "}" :
          _tokens = Belt_Array.concat(tokens, [{
                  TAG: /* Curly */2,
                  _0: /* Close */1
                }]);
          _chars = tail;
          continue ;
      default:
        _tokens = Belt_Array.concat(tokens, [{
                TAG: /* Unid */4,
                _0: $$char
              }]);
        _chars = tail;
        continue ;
    }
  };
}

function parser(param) {
  
}

var machine = "\n  state enabled {\n    toggle => disabled\n  }\n\n  initial state disabled {\n    toggle => enabled\n  }\n";

exports.machine = machine;
exports.lexer = lexer;
exports.parser = parser;
/*  Not a pure module */
